window:
  decorations: buttonless
  padding:
    x: 0
    y: 0

scrolling:
  multiplier: 9

# Font configuration (changes require restart)
font:
  normal:
    family: SauceCodePro Nerd Font
    style: Regular

  bold:
    family: SauceCodePro Nerd Font
    style: Semibold

  # Nerd fonts are subtly broken. Only one italic file can exists, so the others
  # have to be deleted from "Font Book" on macOS, for this to work.
  # https://github.com/ryanoasis/nerd-fonts/pull/717
  italic:
    family: SauceCodePro Nerd Font
    style: Italic

  size: 11.0

  offset:
    x: 0
    y: 0

# Colors
colors:
  primary:
    background: '0x262626'
    foreground: '0xf0f3f4'

  normal:
    black:   '0x3d4f63'
    red:     '0xff6c5c'
    green:   '0x87d195'
    yellow:  '0xffcd8e'
    blue:    '0x98bef6'
    magenta: '0xd5bcf2'
    cyan:    '0x70ceb5'
    white:   '0xdadee1'

  # Default bright alacritty colors
  bright:
    black:   '0x666666'
    red:     '0xff3334'
    green:   '0x9ec400'
    yellow:  '0xe7c547'
    blue:    '0x7aa6da'
    magenta: '0xb77ee0'
    cyan:    '0x54ced6'
    white:   '0xf0f3f4'

  # When true, bold text is drawn using the bright variant of colors.
  draw_bold_text_with_bright_colors: true

env:
  TERM: xterm-256color

shell:
  program: sh
  args:
    - -c
    - if [ -x /usr/libexec/path_helper ]; then eval `/usr/libexec/path_helper -s`; fi; tmux attach || tmux

